# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these for the very latest on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Fabric API - check https://fabricmc.net/develop or Modrinth/CurseForge for the newest
# 26.2 build at time of writing
fabric_version=0.160.0+26.2

# Mod Properties
mod_version=1.0.0
maven_group=club.notben
archives_base_name=fastplace
